# Logger config
logger:
  level: "INFO"
  path: "logs/logfile.log"
# Server config
server:
  host: "127.0.0.1"
  port: "8080"
# Database config
database:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "password"
  name: "banner_rotator"
  SSLMode: "disable"